apiVersion: skaffold/v4beta7
kind: Config

manifests:
  rawYaml:
    - k8s/*.yaml

deploy:
  kubectl: {}

profiles:
  - name: dev
    deploy:
      kubectl:
        defaultNamespace: dev

  - name: prod
    deploy:
      kubectl:
        defaultNamespace: prod
