apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: dev
  annotations:
    deploy.cloud.google.com/skaffold-profile: dev
description: Dev environment
gke:
  cluster: projects/swift-arcadia-484906-v2/locations/us-central1/clusters/k8
---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: prod
  annotations:
    deploy.cloud.google.com/skaffold-profile: prod
description: Prod environment
gke:
  cluster: projects/swift-arcadia-484906-v2/locations/us-central1/clusters/k8
